title: Webpage
author: Cristobal
email: cristobalcuevaslagos@gmail.com
markdown: kramdown
theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
